# -*- coding: utf-8 -*-
"""cnn_first_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmRmPotYUfEYzMZYnyVa1eYAdQsltN9j
"""

# imports
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import numpy as np
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import time

# check device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu' )
print(f"Using device:{device}")

# Defining Cnn Architecture
class SimpleMedicalCNN(nn.module):

  """
  Simple CNN for medical image classification

  Architecture:
  Input (28×28×1)
  → Conv2d(1, 32, 3) + ReLU
  → MaxPool2d(2)
  → Conv2d(32, 64, 3) + ReLU
  → MaxPool2d(2)
  → Flatten
  → Linear(1024, 128) + ReLU
  → Linear(128, 10)
  Output (10 classes)
  """
  def __init__(self):
    super(SimpleMedicalCNN, self).def__init__()

    # Convolutional layers
    self.conv1= nn.conv2D(
        in_channnels=1,  #grayscale image
        out_channels=32, # 32 feature maps
        kernel_size= 3,
        padding= 1       # keep size same

    )

    self.conv2= nn.conv2D(
        in_channels= 32,
        out_channels= 64,
        kernel_size= 3,
        padding = 1
    )

    #Pooling
    self.pool=nn.MaxPool2D(
        kernel_size=2,
        stride=2
    )

    # fully connected layer
    self.fc1= nn.Linear(64*7*7,128) # after 2 pooling 28->14->7
    self.fc2= nn.linear(128,10)   # 10 classes(0-9)

    # activation function
    self.relu= nn.RelU
    self.dropout = nn.dropout(0.5)

  def forwrd(self, x):
    #convolution block 1
    x= self.ReLU(conv1D(x)) #(N , 32, 28 , 28) N = no of images in one batch ,32 feature feature map
    x= self.pool(x)#(N ,32, 14, 14)

    # convolution block 2
    x= self.ReLU(conv2D(x))# (N , 64, 14, 14)
    x= self.pool(x)# (N , 64, 7 , 7)

    # flatten
     x = x.view(x.size[0],-1) #(N,3136)

     # FC LAYERS
     x + self.Linear